### PR TITLE
functools.lrucache() added 

### PR DESCRIPTION
**Pull request by Parth-Vader**
Caching css_to_xpath()'s recently used patterns to improve efficiency.

### CODE REVIEW

**Comment by Parth-Vader** [comment]
The backport works for python 2.7 only, hence the check for python 2.6 fails.

**Comment by Parth-Vader** [comment]
@redapple @eliasdorneles The PR is ready for review.

**Comment by redapple** [comment]
hi @Parth-Vader , I was assuming that this PR would go in https://github.com/scrapy/parsel/ (ref. https://github.com/scrapy/parsel/issues/98)
cssselect is used by more than just scrapy and parsel. I don't think we want to add a dependency for these other users.

**Comment by Parth-Vader** [comment]
@redapple I understand. So what can be done for this PR?

Can scrapy use another branch of cssselect where this could be merged?

**Comment by redapple** [comment]
@Parth-Vader , can this caching not be done in Parsel?
I don't think we want scrapy to use another branch of cssselect?

**Comment by redapple** [comment]
Let's continue in https://github.com/scrapy/parsel/issues/98

**Comment by AlJohri** [comment]
@redapple can this just be changed into an optional dependency and included with the main cssselect? that way Python 3 users can get the performance boost without any additional dependencies. python 2 users can get the perf boost if they happen to have functools32 installed

seems like you would just need to make lru_cache a noop if functools32 is not found

**Comment by redapple** [comment]
I'd rather not add this caching to cssselect.
cssselect does one thing: translate CSS selectors to an XPath expression. Performance was not a design concern I don't think. And I believe parsel could implement it's own caching quite naturally.
By that's just my opinion. @kmike may have other thoughts.

**Comment by kmike** [comment]
I agree with @redapple.

**Pull request closed without merging**
